name: Train ML Model and Save Artifact

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug and Run training script
        run: |
          ls -R  # Perintah ini untuk memunculkan semua daftar file agar kita bisa cek lokasinya
          python preprocessing/automate_Akas.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: Membangun_model/model.pkl
